# Generated by Django 5.0.6 on 2024-06-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_meeting_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
